

import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './navbar/page'
import Fotter from './fotter/page'
import style from "./page.module.css"
import { Provider } from 'react-redux'
import store from './Redux/Store'
import AuthProvider from '@/component/Authprovider/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
    
  
    <AuthProvider>
      <body className={inter.className}>
      <div className={style.headerofnav}>

      <Navbar></Navbar>
      </div>
      
      {children}
       <footer>
         <Fotter></Fotter>
       </footer>
      </body>
      </AuthProvider>
    </html>
  )
}
